kaw393939/webAPI

app/Http/Controllers/Auth/ApiController.php
app/Http/Controllers/Auth/GetAuthUserAPIController.php
app/Http/Controllers/Auth/RegisterAPIController.php
routes/api.php

Refactored register method to its own controller (RegistrationAPIController)

Tasks: Refactored the Register method to RegistrationAPIController

---

package.json
resources/js/App.vue
resources/js/app.js
resources/js/components/Navigation.vue
resources/js/store/index.js
resources/js/store/modules/auth.js
resources/js/views/Login.vue
resources/js/views/PassRecover.vue
resources/js/views/Register.vue

Implemented user validation for the register component.

Reg validation

---

app/Http/Controllers/Auth/GetAuthUserAPIController.php
app/Http/Controllers/Auth/RegisterAPIController.php
app/Http/Requests/EditUserProfileRequest.php
app/Policies/UserProfilePolicy.php
app/Providers/AuthServiceProvider.php
app/User.php
database/migrations/2014_10_12_000000_create_users_table.php
routes/api.php
tests/Feature/EditUserTest.php

Created editAuthUser function with policies and test. Created a saveEditedUser function to update database with edited user info. Also added a bio field to the database, and changed User model

Task: Edit User Profile

---

app/Http/Controllers/UserController.php
app/Http/Resources/UserResource.php
app/Http/Resources/UsersResource.php
routes/api.php
tests/Feature/ShowUserTest.php

added resources for User and implemented userController to display User Information in route /api/users/id

Adding json resource

---

app/Http/Controllers/UserController.php
app/Http/Resources/UserResource.php
app/Http/Resources/UsersResource.php
routes/api.php
tests/Feature/ShowUserTest.php

Revert "Revert "Adding json resource""

---

app/Http/Controllers/UserController.php
app/Http/Resources/UserResource.php
app/Http/Resources/UsersResource.php
routes/api.php
tests/Feature/ShowUserTest.php

using jsonResource for Users/id and Users route

---

app/Events/NewQuestionEvent.php
app/Http/Controllers/QuestionController.php
app/Listeners/NewQuestionListener.php
app/Providers/EventServiceProvider.php
tests/Feature/QuestionsTest.php

Logging for new question creation

Task - New Question Creation Logging

---

app/Http/Controllers/AnswerController.php
app/Http/Requests/AnswerCreateRequest.php
app/Http/Requests/AnswerDeleteRequest.php
app/Http/Requests/AnswerUpdateRequest.php
routes/api.php
tests/Feature/AnswersTest.php

Created create, update and destroy methods for answers, and also created the custom requests, routes and tests.

Answer Methods

---

app/Http/Controllers/Auth/RegisterAPIController.php
app/Http/Requests/RegisterRequest.php
tests/Feature/LogoutTest.php
tests/Feature/RegisterTest.php

Fix: Adjusted registration controller and tests to require first name, last name and bio at registration

Registration Endpoint Fix

---

app/Http/Resources/QuestionResource.php

Task: Hardcoded avatar link, tags, likes and votes to question response

Questions Response

---

app/Http/Controllers/Auth/LogoutAPIController.php

LogoutAPIController

---

app/Http/Controllers/Auth/LoginController.php

LoginController: Beautify & DocBlock

---

app/Http/Controllers/Auth/LoginAPIController.php

LoginAPIController: Beautify & DocBlock

---

app/Http/Controllers/Auth/GetAuthUserAPIController.php

GetAuthUserAPIController: Beautify & DocBlock

---

app/Http/Controllers/Auth/ForgotPasswordController.php

ForgotPasswordController

---

app/Http/Controllers/UserController.php

UserController : Beautify & DocBlock

---

app/Http/Controllers/SpaController.php

SpaController: Beautify & DocBlock

---

app/Http/Controllers/QuestionController.php

QuestionController: Beautify & DocBlock

---

app/Http/Controllers/ProfileController.php

ProfileController: Beautify & DocBlock

---

app/Http/Controllers/Controller.php

Controller : Beautify & DocBlock

---

app/Http/Controllers/Auth/RegisterAPIController.php

RegisterAPIController: Beautify & DocBlock

---

app/log/LogAllRequests.php

LogAllRequests: beautify and docblock

---

app/Events/QuestionEditedEvent.php

QuestionEditedEvent: Beautify & DocBlock

---

app/Events/QuestionDeletedEvent.php

QuestionDeleted: Beautify & Doc Block

---

app/Events/NewQuestionEvent.php

NewQuestionEvent : Beautify & DocBlock

---

app/Events/NewAnswerEvent.php

NewAnswerEvent : Beautify & DocBlock

---

app/Events/LogOutEvent.php

LogOutEvent : Beautify & Doc Block

---

app/Events/LogInEvent.php

Beautified using PSR 2 and added Doc Block, ran unit test

Beautify & Doc Block : LogInEvent

---

app/Events/RegistrationEvent.php

RegistrationEvent : Beautify & DocBlock

---

app/Http/Controllers/Auth/RegisterController.php

RegisterController

---

app/Http/Controllers/Auth/ResetPasswordController.php

ResetPasswordController: Beautify & DocBlock

---

app/Http/Controllers/Auth/VerificationController.php

VerificationController: Beautify & DocBlock
